"""

Revision ID: 45349d759e2f
Revises: 4ba10200cccb
Create Date: 2023-01-22 15:52:50.574029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45349d759e2f'
down_revision = '4ba10200cccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
