"""

Revision ID: 481c1a2a6105
Revises: 45349d759e2f
Create Date: 2023-01-22 15:57:25.591838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481c1a2a6105'
down_revision = '45349d759e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_name_key', ['name'])

    # ### end Alembic commands ###
